# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest
variables:
- group: MusicBotGroup

steps:
- bash: |
    echo $(MUSIC_BOT_TOKEN) all upper
    echo $(music_bot_token) lowercase
  displayName: 'Run a one-line script'

- bash: |
    echo $(MUSIC_BOT_TOKEN) environment
  displayName: 'Run a multi-line script'
  env:
    MUSIC_BOT_TOKEN: $(music_bot_token)
